version: '2'
 
services:
  react:
    container_name: react
    build: ./client
    ports:
      - "3000:3000"
  
  comments:
    container_name: comments
    build: ./comments
    ports:
      - "4001:4001"
 
  event-bus:
    container_name: eventbus
    build: ./event-bus
    ports:
      - "4005:4005"
 
  moderation:
    container_name: moderation
    build: ./moderation
    ports:
      - "4003:4003"
 
  posts:
    container_name: posts
    build: ./posts
    ports:
      - "4000:4000"
 
  query:
    container_name: query
    build: ./query
    ports:
      - "4002:4002"